apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{ include "listmonk.labels" . | nindent 4 }}
data:
  config.toml: |
    [app]
    address = "0.0.0.0:80"

    [db]
    host = {{ include "listmonk.postgresHostname" . | quote }}
    port = 5432
    database = {{ .Values.postgres.database | quote }}
    ssl_mode = "disable"
    max_open = 25
    max_idle = 25
    max_lifetime = "300s"
